<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="">
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->getSkinUrl('images/ico/apple-touch-icon-144x144-precomposed.png') ?>">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->getSkinUrl('images/ico/apple-touch-icon-114x114-precomposed.png') ?>">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->getSkinUrl('images/ico/apple-touch-icon-72x72-precomposed.png') ?>">
<link rel="apple-touch-icon-precomposed" href="<?php echo $this->getSkinUrl('images/ico/apple-touch-icon-57x57-precomposed.png') ?>">

<?php
// check page template for catalog pages and run a product search function
echo $socialMetaTags =  $this->createSocialMetaTags( Mage::app()->getFrontController()->getRequest()->getControllerName() );

// ... rest of head.phtml goes here
