<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@storefrontconsulting.com so we can send you a copy immediately.
 *
 * @copyright	(C)Copyright 2013 StoreFront Consulting, Inc (http://www.StoreFrontConsulting.com/)
 * @author		Dennis Rogers
 */

// Select slider ID from geolocation
$sliderId = Mage::getBlockSingleton('geolocation/geolocation')->getGeolocationBlocks('homepage-ads', 'aw_islider');

// checks if ID was called
if ( $sliderId) {
    $this->setId( $sliderId);
}

/**
* Display AW iSlider markup
*/
 // get slider images
$block = $this->getSliderCollection()->getFirstItem();

if($block){
    $images = $block->getImagesCollection()->addFieldToFilter("status", 1)->sortBySortOrder();
};

echo "<div class=\"row hidden-phone\">";

    if($block && $images->count()) {
        $i=1;
        foreach($images as $image) {
            if($image->getData('type') == AW_Islider_Model_Source_Images_Type::FILE) {
                $src =  Mage::app()->getStore()->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).Mage::helper('awislider/files')->getFolderName().DS.$image->getData('location');
            } else {
                $src =  $image->getData('location');
            };

            echo "<div class=\"span3\">";
            echo    "<a href=\"{$image->getUrl()}\" title=\"{$image->getTitle()}\">";
            echo        "<img style=\"width:100%;\" src=\"{$src}\" alt=\"{$image->getTitle()}\">";
            echo    "</a>";
            echo"</div>";
            if($i >= 4) break; $i++;
        }; // end foreach loop
    } // end if statement;
echo "</div>";
